/**
 * Configuration version of all build dependencies
 */
object BuildDependenciesVersions {
    const val KOTLIN = "1.3.72"
    const val APPCOMPAT = "1.1.0"
    const val MATERIAL = "1.1.0-beta01"
    const val BIOMETRIC = "1.0.1"
    const val SECURITY = "1.0.0-beta01"
    const val COROUTINES = "1.3.3"
    const val CARD_VIEW = "1.1.0"
    const val ROOM = "2.2.3"
    const val RECYCLE_VIEW = "1.2.0-alpha02"
    const val NAVIGATION = "2.3.0-alpha04"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT = "1.2.4"
    const val CONSTRAIN_LAYOUT = "2.0.0-beta4"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-rc01"
    const val PAGING = "2.1.1"
    const val KOIN = "2.1.4"
    const val RETROFIT = "2.7.0"
    const val COIL = "0.9.5"
    const val PLAY_CORE = "1.7.0"
    const val LEAKCANARY = "2.0"
    const val DATABINDING = "3.1.4"
    const val AUTO_SERVICE = "1.0-rc4"
    const val SDP = "1.0.6"
    const val ANIMATION = "1.0.0"
    const val RX = "3.0.0"
    const val FLEXIBLE_ADAPTER = "5.1.0"
    const val FLEXIBLE_ADAPTER_UI = "1.0.0"
    const val FLEXIBLE_ADAPTER_LIVE_DATA = "1.0.0-b3"
    const val FLEXIBLE_ADAPTER_BINDING = "1.0.0"
    const val UTILS = "1.27.0"
    const val INLINE_ACTIVITY_RESULT = "1.0.3"
    const val BUTTER_KNIFE = "10.2.1"
    const val TED_PERMISSION = "2.2.0"
    const val GLIDE = "4.9.0"
    const val CAMERA2 = "1.0.0-alpha03"
    const val BROWSER = "1.2.0"
    const val FLEXBOX = "2.0.1"
    const val WORK_MANAGE = "2.3.4"
    const val TIMBER = "4.7.1"
    const val INSTANT_APPS = "1.1.0"
    const val DAGGER_ANDROID = "2.27"
    const val GSON = "2.8.6"
    const val OK_HTTP = "4.6.0"

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.14.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.0-alpha02"
    const val MOCK_WEB_SERVER = "4.2.2"
}
