package dependencies

/**
 * Project dependencies, makes it easy to include external binaries or
 * other library modules to build.
 */
object Dependencies {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${BuildDependenciesVersions.KOTLIN}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${BuildDependenciesVersions.APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${BuildDependenciesVersions.MATERIAL}"
    const val BIOMETRIC = "androidx.biometric:biometric:${BuildDependenciesVersions.BIOMETRIC}"
    const val SECURITY = "androidx.security:security-crypto:${BuildDependenciesVersions.SECURITY}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${BuildDependenciesVersions.COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${BuildDependenciesVersions.COROUTINES}"
    const val CARD_VIEW = "androidx.cardview:cardview: ${BuildDependenciesVersions.CARD_VIEW}"
    const val ROOM = "androidx.room:room-runtime:${BuildDependenciesVersions.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${BuildDependenciesVersions.ROOM}"
    const val RECYCLE_VIEW = "androidx.recyclerview:recyclerview:${BuildDependenciesVersions.RECYCLE_VIEW}"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${BuildDependenciesVersions.NAVIGATION}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${BuildDependenciesVersions.NAVIGATION}"
    const val NAVIGATION_DYNAMIC_FEATURE = "androidx.navigation:navigation-dynamic-features-fragment:${BuildDependenciesVersions.NAVIGATION}"
    const val LIFECYCLE_EXTENSIONS = "androidx.lifecycle:lifecycle-extensions:${BuildDependenciesVersions.LIFECYCLE}"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${BuildDependenciesVersions.LIFECYCLE}"
    const val LIFECYCLE_LIVE_DATA = "androidx.lifecycle:lifecycle-livedata:${BuildDependenciesVersions.LIFECYCLE}"
    const val CORE_KTX = "androidx.core:core-ktx:${BuildDependenciesVersions.CORE_KTX}"
    const val FRAGMENT = "androidx.fragment:fragment:${BuildDependenciesVersions.FRAGMENT}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${BuildDependenciesVersions.FRAGMENT}"
    const val CONSTRAIN_LAYOUT = "androidx.constraintlayout:constraintlayout:${BuildDependenciesVersions.CONSTRAIN_LAYOUT}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${BuildDependenciesVersions.SWIPE_REFRESH_LAYOUT}"
    const val PAGING = "androidx.paging:paging-runtime-ktx:${BuildDependenciesVersions.PAGING}"
    const val KOIN = "org.koin:koin-android:${BuildDependenciesVersions.KOIN}"
    const val KOIN_VIEW_MODEL = "org.koin:koin-androidx-viewmodel:${BuildDependenciesVersions.KOIN}"
    const val KOIN_FRAGMENT = "org.koin:koin-androidx-fragment:${BuildDependenciesVersions.KOIN}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${BuildDependenciesVersions.RETROFIT}"
    const val RETROFIT_RXJAVA = "com.squareup.retrofit2:adapter-rxjava2:${BuildDependenciesVersions.RETROFIT}"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-gson:${BuildDependenciesVersions.RETROFIT}"
    const val RETROFIT_SCALARS = "com.squareup.retrofit2:converter-scalars:${BuildDependenciesVersions.RETROFIT}"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${BuildDependenciesVersions.OK_HTTP}"
    const val COIL = "io.coil-kt:coil:${BuildDependenciesVersions.COIL}"
    const val PLAY_CORE = "com.google.android.play:core:${BuildDependenciesVersions.PLAY_CORE}"
    const val ANIMATION = "com.mikhaellopez:rxanimation:${BuildDependenciesVersions.ANIMATION}"
    const val RX_JAVA = "io.reactivex.rxjava3:rxjava:${BuildDependenciesVersions.RX}"
    const val RX_ANDROID = "io.reactivex.rxjava3:rxandroid:${BuildDependenciesVersions.RX}"
    const val RX_KOTLIN = "io.reactivex.rxjava3:rxkotlin:${BuildDependenciesVersions.RX}"
    const val FLEXIBLE_ADAPTER = "eu.davidea:flexible-adapter:${BuildDependenciesVersions.FLEXIBLE_ADAPTER}"
    const val FLEXIBLE_ADAPTER_UI = "eu.davidea:flexible-adapter-ui:${BuildDependenciesVersions.FLEXIBLE_ADAPTER_UI}"
    const val FLEXIBLE_ADAPTER_LIVE_DATA = "eu.davidea:flexible-adapter-livedata:${BuildDependenciesVersions.FLEXIBLE_ADAPTER_LIVE_DATA}"
    const val FLEXIBLE_ADAPTER_BINDING = "eu.davidea:flexible-adapter-databinding:${BuildDependenciesVersions.FLEXIBLE_ADAPTER_BINDING}"
    const val UTILS = "com.blankj:utilcodex:${BuildDependenciesVersions.UTILS}"
    const val INLINE_ACTIVITY_RESULT = "com.github.florent37:inline-activity-result-kotlin:${BuildDependenciesVersions.INLINE_ACTIVITY_RESULT}"
    const val BUTTER_KNIFE = "com.jakewharton:butterknife:${BuildDependenciesVersions.BUTTER_KNIFE}"
    const val TED_PERMISSION = "gun0912.ted:tedpermission:${BuildDependenciesVersions.TED_PERMISSION}"
    const val GLIDE = "com.github.bumptech.glide:glide:${BuildDependenciesVersions.GLIDE}"
    const val CAMERA2 = "androidx.camera:camera-core:${BuildDependenciesVersions.CAMERA2}"
    const val CAMERA2_CORE = "androidx.camera:camera-camera2:${BuildDependenciesVersions.CAMERA2}"
    const val BROWSER = "androidx.browser:browser:${BuildDependenciesVersions.BROWSER}"
    const val FLEXBOX = "com.google.android:flexbox:${BuildDependenciesVersions.FLEXBOX}"
    const val WORK_MANAGE = "androidx.work:work-runtime:${BuildDependenciesVersions.WORK_MANAGE}"
    const val WORK_MANAGE_KTX = "androidx.work:work-runtime-ktx:${BuildDependenciesVersions.WORK_MANAGE}"
    const val TIMBER = "com.jakewharton.timber:timber:${BuildDependenciesVersions.TIMBER}"
    const val INSTANT_APPS = "com.google.android.instantapps:instantapps:${BuildDependenciesVersions.INSTANT_APPS}"
    const val DAGGER_ANDROID = "com.google.dagger:dagger-android:${BuildDependenciesVersions.DAGGER_ANDROID}"
    const val DAGGER_ANDROID_SUPPORT = "com.google.dagger:dagger-android-support:${BuildDependenciesVersions.DAGGER_ANDROID}"
    const val DAGGER_ANDROID_COMPILER = "com.google.dagger:dagger-compiler:${BuildDependenciesVersions.DAGGER_ANDROID}"
    const val DAGGER_ANDROID_PROCESSOR = "com.google.dagger:dagger-android-processor:${BuildDependenciesVersions.DAGGER_ANDROID}"
    const val GSON = "com.google.code.gson:gson:${BuildDependenciesVersions.GSON}"
    const val OK_HTTP = "com.squareup.okhttp3:okhttp:${BuildDependenciesVersions.OK_HTTP}"
    const val GOOGLE_BILLING = "com.android.billingclient:billing:2.2.1"

    const val PLAY_SERVICES_BASE = "com.google.android.gms:play-services-base:17.2.1"
    const val PLAY_SERVICES_AUTH = "com.google.android.gms:play-services-auth:17.0.0"
    const val PLAY_SERVICES_AUTH_PHONE = "com.google.android.gms:play-services-auth-api-phone:17.4.0"
    const val PLAY_SERVICES_MAP  = "com.google.android.gms:play-services-maps:17.0.0"
}
